plugins {
    alias(libs.plugins.protobuf)
}

group = 'com.ahicode.bidflow.common'
version = '1.0-SNAPSHOT'

dependencies {
    implementation libs.grpc.protobuf
    implementation libs.grpc.stub

    compileOnly "org.apache.tomcat:annotations-api:6.0.53"
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.25.1"
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                java { option "lite" }
            }
        }
    }
}

sourceSets {
    main {
        proto {
            srcDir 'src/main/proto'
        }
    }
}